--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: k8demo
  namespace: default
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      bb: web
  template: 
    metadata: 
      labels: 
        bb: web
    spec: 
      containers: 
        - 
          image: vishnu-devops20/dockerapp:latest
          name: k8demo
--- 
apiVersion: v1
kind: Service
metadata: 
  name: k8demo
  namespace: default
spec: 
  ports: 
    - 
      port: 8008
      targetPort: 8080
  selector: 
    bb: web
  type: LoadBalancer
