--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: k8jenkinsdemo
  namespace: default
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      bb: web
  template: 
    metadata: 
      labels: 
        bb: web
    spec: 
      containers: 
        - 
          image: gcr.io/zinc-gist-283714/dockerapp
          name: k8jenkinsdemo
--- 
apiVersion: v1
kind: Service
metadata: 
  name: k8jenkinsdemo
  namespace: default
spec: 
  ports: 
    - 
      port: 8002
      targetPort: 8080
  selector: 
    bb: web
  type: LoadBalancer
